// <auto-generated />
using System;
using Jorteck.Toolbox;
using Jorteck.Toolbox.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jorteck.Toolbox.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20211106235736_AddBlueprintModel")]
    partial class AddBlueprintModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Jorteck.Toolbox.BlueprintModel", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("BlueprintData")
                        .HasColumnType("BLOB");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Type", "Name");

                    b.ToTable("BlueprintPresets");
                });
#pragma warning restore 612, 618
        }
    }
}
